spring:
  application:
    name: 'parkingdomain'
  datasource:
    url: jdbc:postgresql://localhost:5432/parkingdomain
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  jooq:
    sql-dialect: postgres

job:
  calling-external-cleaning-service-policy-job:
    cron-expression: "0 0 13 * * ?"
  making-requests-valid-job:
    cron-expression: "0 0 1 * * ?"
  activating-reservations-job:
    cron-expression: "0 */1 * * * ?"
  removing-not-used-reservations-job:
    cron-expression: "0 */1 * * * ?"
  notifying-about-releasing-job:
    cron-expression: "0 */5 * * * ?"

business:
  cleaning:
    number-of-dirty-parking-spots-to-call-external-service: 10
    number-of-drives-away-to-consider-parking-spot-dirty: 20
  parking:
    minutes-to-consider-reservation-active: 60
    minutes-to-consider-reservation-not-used: 15
    minutes-to-release-occupation-because-of-reservations: 30
  requesting:
    creating-time-slots:
      morning-start-hour: 5
      morning-end-hour: 17
      evening-start-hour: 18
      evening-end-hour: 24

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

server:
  tomcat:
    mbeanregistry:
      enabled: true
