spring:
  datasource:
    url: jdbc:h2:mem:parking-domain
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

logging:
  level:
    pl.cezarysanecki.parkingdomain: DEBUG
